"""litigation_subjects_added

Revision ID: 0dcb1266bbf6
Revises: d6922bf73ef6
Create Date: 2022-02-16 12:04:30.497462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcb1266bbf6'
down_revision = 'd6922bf73ef6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('litigation_subject',
    sa.Column('litigation_id', sa.Integer(), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.construction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['litigation_id'], ['courts.litigation.litigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('litigation_id', 'construction_id', name='litigation_subject_pk'),
    schema='courts'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('litigation_subject', schema='courts')
    # ### end Alembic commands ###
