"""New table participant status

Revision ID: 2ca61b95cb38
Revises: bf919412aa89
Create Date: 2021-10-27 16:14:57.238526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca61b95cb38'
down_revision = 'bf919412aa89'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_statuses',
    sa.Column('participant_statuses_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('participant_statuses_id'),
    sa.UniqueConstraint('fullname'),
    schema='courts'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_statuses', schema='courts')
    # ### end Alembic commands ###
