"""create courts

Revision ID: 36ceacef8ed9
Revises: 645e2fdfe156
Create Date: 2021-10-19 12:45:21.032269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ceacef8ed9'
down_revision = '645e2fdfe156'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema courts')
    op.create_table('courts',
    sa.Column('courts_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('courts_id'),
    sa.UniqueConstraint('fullname'),
    schema='courts'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courts', schema='courts')
    op.execute('drop schema courts')
    # ### end Alembic commands ###
