"""litigation_documents_added

Revision ID: 4ecbd4700bdb
Revises: 0dcb1266bbf6
Create Date: 2022-02-16 15:50:29.138474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ecbd4700bdb'
down_revision = '0dcb1266bbf6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('litigation_documents',
    sa.Column('litigation_documents_id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.VARCHAR(length=40), nullable=False),
    sa.Column('doc_date', sa.DATE(), nullable=False),
    sa.Column('doc_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('litigation_id', sa.Integer(), nullable=False),
    sa.Column('doctypes_id', sa.Integer(), nullable=False),
    sa.Column('idfilestorage', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['doctypes_id'], ['doctypes.doctypes_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idfilestorage'], ['filestorage.idfilestorage'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['litigation_id'], ['courts.litigation.litigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('litigation_documents_id'),
    sa.UniqueConstraint('litigation_id', 'doctypes_id', 'doc_number', 'doc_date', name='litigation_document_unique'),
    schema='courts'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('litigation_documents', schema='courts')
    # ### end Alembic commands ###
