"""Fix table officials

Revision ID: 5f1b055c83d3
Revises: d942c26c0733
Create Date: 2021-12-16 12:33:27.970903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f1b055c83d3'
down_revision = 'd942c26c0733'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officials', sa.Column('class_ranks_id', sa.Integer(), nullable=True), schema='organization')
    op.add_column('officials', sa.Column('idfilestorage', postgresql.UUID(), nullable=True), schema='organization')
    op.create_foreign_key(None, 'officials', 'class_ranks', ['class_ranks_id'], ['class_ranks_id'], source_schema='organization', referent_schema='organization')
    op.create_foreign_key(None, 'officials', 'filestorage', ['idfilestorage'], ['idfilestorage'], source_schema='organization', ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'officials', schema='organization', type_='foreignkey')
    op.drop_constraint(None, 'officials', schema='organization', type_='foreignkey')
    op.drop_column('officials', 'idfilestorage', schema='organization')
    op.drop_column('officials', 'class_ranks_id', schema='organization')
    # ### end Alembic commands ###
