"""create reason_stopping

Revision ID: 645e2fdfe156
Revises: 6e9903d3477e
Create Date: 2021-10-14 09:47:41.029813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645e2fdfe156'
down_revision = '6e9903d3477e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reason_stopping',
    sa.Column('reasons_stopping_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False, comment='Полное название'),
    sa.PrimaryKeyConstraint('reasons_stopping_id'),
    sa.UniqueConstraint('fullname')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reason_stopping')
    # ### end Alembic commands ###
