"""Create construction critial categories and update construction

Revision ID: 6e9903d3477e
Revises: 2e1edf4ffc3b
Create Date: 2021-10-12 11:24:17.676053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9903d3477e'
down_revision = '2e1edf4ffc3b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critical_categories',
    sa.Column('critical_categories_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('critical_categories_id'),
    sa.UniqueConstraint('fullname')
    )
    op.add_column('construction', sa.Column('critical_categories_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'construction', 'critical_categories', ['critical_categories_id'], ['critical_categories_id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'construction', type_='foreignkey')
    op.drop_column('construction', 'critical_categories_id')
    op.drop_table('critical_categories')
    # ### end Alembic commands ###
