"""Create work trip files

Revision ID: 88a8932302e4
Revises: 6e9903d3477e
Create Date: 2021-10-20 14:14:46.614024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88a8932302e4'
down_revision = '6e9903d3477e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_trip_files',
    sa.Column('idfilestorage', postgresql.UUID(), nullable=False),
    sa.Column('work_trips_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['idfilestorage'], ['filestorage.idfilestorage'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_trips_id'], ['work_trips.work_trips_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idfilestorage')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_trip_files')
    # ### end Alembic commands ###
