"""init migration

Revision ID: aee298720d4f
Revises: 
Create Date: 2021-09-21 16:57:54.656838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aee298720d4f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # create schemas
    op.execute('create schema "organization"')
    op.execute('create schema "state_contract"')
    op.execute('create schema "military_unit"')
    op.execute('create schema "miv"')
    op.execute('create schema "logs"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OKSM',
    sa.Column('oksm_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.CHAR(length=3), nullable=False),
    sa.Column('shortname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('alpha2', sa.CHAR(length=2), nullable=False),
    sa.Column('alpha3', sa.CHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('oksm_id'),
    sa.UniqueConstraint('alpha2'),
    sa.UniqueConstraint('alpha3'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('shortname')
    )
    op.create_table('commission',
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('index_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('commission_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('construction_categories',
    sa.Column('construction_categories_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('construction_categories_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('construction_stages',
    sa.Column('construction_stages_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('ref_construction_stages_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ref_construction_stages_id'], ['construction_stages.construction_stages_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('construction_stages_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('construction_subcategories',
    sa.Column('construction_subcategories_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('construction_subcategories_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('construction_types',
    sa.Column('construction_types_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('construction_types_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('coordinates',
    sa.Column('coordinates_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('zoom', sa.Integer(), nullable=False),
    sa.Column('mark', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('coordinates_id')
    )
    op.create_table('doctypes',
    sa.Column('doctypes_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=40), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('doctypes_id'),
    sa.UniqueConstraint('code', 'fullname', name='doctypes_unique')
    )
    op.create_table('element_types',
    sa.Column('element_types_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('element_types_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('fias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aoid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('region', sa.VARCHAR(length=64), nullable=True, comment='субъект РФ'),
    sa.Column('area', sa.VARCHAR(length=64), nullable=True, comment='район'),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True, comment='город'),
    sa.Column('settlement', sa.VARCHAR(length=64), nullable=True, comment='населенный пункт'),
    sa.Column('street', sa.VARCHAR(length=64), nullable=True, comment='улица'),
    sa.Column('home', sa.VARCHAR(length=64), nullable=True, comment='дом'),
    sa.Column('body', sa.VARCHAR(length=64), nullable=True, comment='корпус'),
    sa.Column('structure', sa.VARCHAR(length=64), nullable=True, comment='строение'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aoid')
    )
    op.create_table('filestorage',
    sa.Column('idfilestorage', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('uri', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('mimeType', sa.VARCHAR(length=45), nullable=True),
    sa.Column('createdOn', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('authorid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idfilestorage')
    )
    op.create_table('inspections',
    sa.Column('inspections_id', sa.Integer(), nullable=False),
    sa.Column('insp_date', sa.DATE(), nullable=False),
    sa.Column('insp_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('inspector', sa.VARCHAR(length=100), nullable=False),
    sa.Column('insp_result', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('inspections_id'),
    sa.UniqueConstraint('insp_date', 'insp_name', name='inspection_unique')
    )
    op.create_table('leadership_positions',
    sa.Column('leadership_positions_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=40), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('leadership_positions_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('location_types',
    sa.Column('location_types_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('location_types_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('db_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('error_raw', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='logs'
    )
    op.create_table('measure_units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('unit_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('unit_code', 'unit_name', name='measure_units_unique')
    )
    op.create_table('meeting',
    sa.Column('meetings_type_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('meetings_type_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('combatarm',
    sa.Column('idcombatarm', sa.CHAR(length=3), nullable=False),
    sa.Column('namecombatarm', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idcombatarm'),
    schema='military_unit'
    )
    op.create_table('keyword',
    sa.Column('idkeyword', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namekeyword', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idkeyword'),
    schema='military_unit'
    )
    op.create_table('militarycity',
    sa.Column('idmilitarycity', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namemilitarycity', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idmilitarycity'),
    schema='military_unit'
    )
    op.create_table('purposemu',
    sa.Column('idpurpose', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namepurpose', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idpurpose'),
    schema='military_unit'
    )
    op.create_table('sortarmedforces',
    sa.Column('idsortaf', sa.CHAR(length=3), nullable=False),
    sa.Column('namesortaf', sa.VARCHAR(length=255), nullable=False),
    sa.Column('snamesortaf', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('idsortaf'),
    schema='military_unit'
    )
    op.create_table('miv_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('dt_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('message_id', postgresql.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='miv'
    )
    op.create_table('storage',
    sa.Column('uid', postgresql.UUID(), nullable=False),
    sa.Column('type', sa.Enum('json', 'binary', name='typeenum'), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dt_received', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'type', name='storage_pk'),
    schema='miv'
    )
    op.create_table('object_categories',
    sa.Column('object_categories_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('object_categories_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('military_ranks',
    sa.Column('military_ranks_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('military_ranks_id'),
    schema='organization'
    )
    op.create_table('organizations',
    sa.Column('organizations_id', postgresql.UUID(), nullable=False),
    sa.Column('par_number', sa.Integer(), nullable=True),
    sa.Column('org_sign', sa.BOOLEAN(), nullable=False),
    sa.Column('parent_organizations_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_organizations_id'], ['organization.organizations.organizations_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organizations_id'),
    schema='organization'
    )
    op.create_table('progress_statuses',
    sa.Column('progress_statuses_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('progress_statuses_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('realty_types',
    sa.Column('realty_types_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('realty_types_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('contract_statuses',
    sa.Column('contract_statuses_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('contract_statuses_id'),
    sa.UniqueConstraint('fullname'),
    schema='state_contract'
    )
    op.create_table('contract_worktypes',
    sa.Column('contract_worktypes_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('contract_worktypes_id'),
    sa.UniqueConstraint('fullname'),
    schema='state_contract'
    )
    op.create_table('work_types',
    sa.Column('work_types_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('work_types_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('zones',
    sa.Column('zones_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('zones_id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('construction_companies',
    sa.Column('construction_companies_id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('address_full', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=True),
    sa.Column('email', sa.VARCHAR(length=80), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.Integer(), nullable=True),
    sa.Column('services', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('id_fias', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_fias'], ['fias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('construction_companies_id'),
    sa.UniqueConstraint('shortname', 'fullname', name='construction_companies_unique')
    )
    op.create_table('inspection_files',
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('idfilestorage', postgresql.UUID(), nullable=False),
    sa.Column('inspections_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idfilestorage'], ['filestorage.idfilestorage'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspections_id'], ['inspections.inspections_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idfilestorage')
    )
    op.create_table('namemilitaryunit',
    sa.Column('idnamemu', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namemu', sa.VARCHAR(length=250), nullable=False),
    sa.Column('snamemu', sa.VARCHAR(length=20), nullable=True),
    sa.Column('idkeyword', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idkeyword'], ['military_unit.keyword.idkeyword'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idnamemu'),
    schema='military_unit'
    )
    op.create_table('object_categories_list',
    sa.Column('object_categories_list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zones_id', sa.Integer(), nullable=False),
    sa.Column('object_categories_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_categories_id'], ['object_categories.object_categories_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zones_id'], ['zones.zones_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_categories_list_id'),
    sa.UniqueConstraint('zones_id', 'object_categories_id', name='object_categories_list_unique')
    )
    op.create_table('officials',
    sa.Column('officials_id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=40), nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=40), nullable=True),
    sa.Column('middlename', sa.VARCHAR(length=40), nullable=True),
    sa.Column('begin_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=True),
    sa.Column('secure_channel', sa.VARCHAR(length=40), nullable=True),
    sa.Column('email', sa.VARCHAR(length=80), nullable=True),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('organizations_id', postgresql.UUID(), nullable=False),
    sa.Column('military_ranks_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['military_ranks_id'], ['organization.military_ranks.military_ranks_id'], ),
    sa.ForeignKeyConstraint(['organizations_id'], ['organization.organizations.organizations_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('officials_id'),
    schema='organization'
    )
    op.create_table('organization_documents',
    sa.Column('organization_documents_id', sa.Integer(), nullable=False),
    sa.Column('doc_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('doc_date', sa.DATE(), nullable=False),
    sa.Column('doc_number', sa.VARCHAR(length=40), nullable=True),
    sa.Column('organizations_id', postgresql.UUID(), nullable=False),
    sa.Column('doctypes_id', sa.Integer(), nullable=False),
    sa.Column('idfilestorage', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['doctypes_id'], ['doctypes.doctypes_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idfilestorage'], ['filestorage.idfilestorage'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizations_id'], ['organization.organizations.organizations_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_documents_id'),
    sa.UniqueConstraint('organizations_id', 'doctypes_id', 'doc_date', 'doc_number', name='organization_documents_unique'),
    schema='organization'
    )
    op.create_table('organizations_history',
    sa.Column('organizations_history_id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('address_legal', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('address_actual', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('functions', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('inn', sa.VARCHAR(length=20), nullable=True),
    sa.Column('kpp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ogrn', sa.VARCHAR(length=20), nullable=True),
    sa.Column('begin_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('organizations_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organizations_id'], ['organization.organizations.organizations_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organizations_history_id'),
    sa.UniqueConstraint('organizations_id', 'begin_date', name='organizations_history_ak'),
    schema='organization'
    )
    op.create_table('protocol',
    sa.Column('protocol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_num', sa.VARCHAR(length=20), nullable=False),
    sa.Column('protocol_date', sa.Date(), nullable=False),
    sa.Column('protocol_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('note', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('meetings_type_id', sa.Integer(), nullable=True),
    sa.Column('idfilestorage', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['idfilestorage'], ['filestorage.idfilestorage'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meetings_type_id'], ['meeting.meetings_type_id'], ),
    sa.PrimaryKeyConstraint('protocol_id')
    )
    op.create_table('subcategories_list',
    sa.Column('subcategories_list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('construction_categories_id', sa.Integer(), nullable=False),
    sa.Column('construction_subcategories_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_categories_id'], ['construction_categories.construction_categories_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['construction_subcategories_id'], ['construction_subcategories.construction_subcategories_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subcategories_list_id'),
    sa.UniqueConstraint('construction_categories_id', 'construction_subcategories_id', name='subcategories_list_unique')
    )
    op.create_table('military_unit',
    sa.Column('idMU', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vChNumber', sa.VARCHAR(length=4), nullable=True),
    sa.Column('codeNameMU', sa.VARCHAR(length=5), nullable=True),
    sa.Column('pidMU', sa.Integer(), nullable=True),
    sa.Column('idNameMU', sa.Integer(), nullable=False),
    sa.Column('idPurpose', sa.Integer(), nullable=False),
    sa.Column('idMilitaryCity', sa.Integer(), nullable=True),
    sa.Column('idSortAF', sa.VARCHAR(length=2), nullable=False),
    sa.Column('idCombatArm', sa.CHAR(length=3), nullable=False),
    sa.ForeignKeyConstraint(['idCombatArm'], ['military_unit.combatarm.idcombatarm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idMilitaryCity'], ['military_unit.militarycity.idmilitarycity'], ),
    sa.ForeignKeyConstraint(['idNameMU'], ['military_unit.namemilitaryunit.idnamemu'], ),
    sa.ForeignKeyConstraint(['idPurpose'], ['military_unit.purposemu.idpurpose'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idSortAF'], ['military_unit.sortarmedforces.idsortaf'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pidMU'], ['military_unit.military_unit.idMU'], ),
    sa.PrimaryKeyConstraint('idMU'),
    schema='military_unit'
    )
    op.create_table('work_trips',
    sa.Column('work_trips_id', sa.Integer(), nullable=False),
    sa.Column('trip_date', sa.DATE(), nullable=False),
    sa.Column('trip_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('escort_officer', sa.VARCHAR(length=100), nullable=False),
    sa.Column('leadership_positions_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leadership_positions_id'], ['leadership_positions.leadership_positions_id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.protocol_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('work_trips_id')
    )
    op.create_table('construction',
    sa.Column('construction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=40), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('address_full', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('department', sa.VARCHAR(length=255), nullable=True),
    sa.Column('officer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('technical_spec', sa.Boolean(), nullable=False),
    sa.Column('price_calc', sa.Boolean(), nullable=False),
    sa.Column('deletion_mark', sa.Boolean(), nullable=False),
    sa.Column('construction_categories_id', sa.Integer(), nullable=True),
    sa.Column('subcategories_list_id', sa.Integer(), nullable=True),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('idMU', sa.Integer(), nullable=True),
    sa.Column('military_district_id', sa.Integer(), nullable=False),
    sa.Column('object_amount', sa.Integer(), nullable=False),
    sa.Column('construction_types_id', sa.Integer(), nullable=True),
    sa.Column('location_types_id', sa.Integer(), nullable=True),
    sa.Column('construction_companies_id', sa.Integer(), nullable=False),
    sa.Column('oksm_id', sa.Integer(), nullable=True),
    sa.Column('coordinates_id', sa.Integer(), nullable=True),
    sa.Column('id_fias', sa.Integer(), nullable=True),
    sa.Column('organizations_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['commission_id'], ['commission.commission_id'], ),
    sa.ForeignKeyConstraint(['construction_categories_id'], ['construction_categories.construction_categories_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['construction_companies_id'], ['construction_companies.construction_companies_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['construction_types_id'], ['construction_types.construction_types_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coordinates_id'], ['coordinates.coordinates_id'], ),
    sa.ForeignKeyConstraint(['idMU'], ['military_unit.military_unit.idMU'], ),
    sa.ForeignKeyConstraint(['id_fias'], ['fias.id'], ),
    sa.ForeignKeyConstraint(['location_types_id'], ['location_types.location_types_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['military_district_id'], ['military_unit.military_unit.idMU'], ),
    sa.ForeignKeyConstraint(['oksm_id'], ['OKSM.oksm_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizations_id'], ['organization.organizations.organizations_id'], ),
    sa.ForeignKeyConstraint(['subcategories_list_id'], ['subcategories_list.subcategories_list_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('construction_id'),
    sa.UniqueConstraint('project_code')
    )
    op.create_table('construction_documents',
    sa.Column('construction_documents_id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.VARCHAR(length=40), nullable=False),
    sa.Column('doc_date', sa.DATE(), nullable=False),
    sa.Column('valid_until', sa.DATE(), nullable=True),
    sa.Column('doc_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('doctypes_id', sa.Integer(), nullable=False),
    sa.Column('idfilestorage', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.construction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctypes_id'], ['doctypes.doctypes_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idfilestorage'], ['filestorage.idfilestorage'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('construction_documents_id')
    )
    op.create_table('construction_dynamics',
    sa.Column('construction_dynamics_id', sa.Integer(), nullable=False),
    sa.Column('reporting_date', sa.DATE(), nullable=False),
    sa.Column('from_sakura', sa.Boolean(), nullable=False),
    sa.Column('update_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('people_plan', sa.Integer(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('equipment_plan', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.Integer(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=100), nullable=True),
    sa.Column('problems', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.construction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('construction_dynamics_id'),
    sa.UniqueConstraint('reporting_date', 'construction_id', 'from_sakura', name='construction_dynamics_ak')
    )
    op.create_table('construction_objects',
    sa.Column('construction_objects_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_code', sa.VARCHAR(length=40), nullable=False),
    sa.Column('object_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('generalplan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('building_volume', sa.DECIMAL(precision=17, scale=3), nullable=True),
    sa.Column('floors_amount', sa.Integer(), nullable=True),
    sa.Column('fact_date', sa.Date(), nullable=True),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('zones_id', sa.Integer(), nullable=True),
    sa.Column('object_categories_list_id', sa.Integer(), nullable=True),
    sa.Column('construction_stages_id', sa.Integer(), nullable=True),
    sa.Column('coordinates_id', sa.Integer(), nullable=True),
    sa.Column('realty_types_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.construction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['construction_stages_id'], ['construction_stages.construction_stages_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coordinates_id'], ['coordinates.coordinates_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_categories_list_id'], ['object_categories_list.object_categories_list_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['realty_types_id'], ['realty_types.realty_types_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zones_id'], ['zones.zones_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('construction_objects_id'),
    sa.UniqueConstraint('object_code')
    )
    op.create_table('inspection_objects',
    sa.Column('inspections_id', sa.Integer(), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.construction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspections_id'], ['inspections.inspections_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspections_id', 'construction_id', name='inspection_objects_pk')
    )
    op.create_table('contracts',
    sa.Column('contracts_id', sa.Integer(), nullable=False),
    sa.Column('contract_num', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contract_date', sa.DATE(), nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=25), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('contract_sum', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('paid_sum', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('accepted_sum', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('receivables', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('plan_sum', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=True),
    sa.Column('contract_statuses_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.construction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_statuses_id'], ['state_contract.contract_statuses.contract_statuses_id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['construction_companies.construction_companies_id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['construction_companies.construction_companies_id'], ),
    sa.PrimaryKeyConstraint('contracts_id'),
    sa.UniqueConstraint('contract_num', 'identifier', name='contracts_ak'),
    schema='state_contract'
    )
    op.create_table('visited_objects',
    sa.Column('work_trips_id', sa.Integer(), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.construction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_trips_id'], ['work_trips.work_trips_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_trips_id', 'construction_id', name='visited_objects_pk')
    )
    op.create_table('construction_progress',
    sa.Column('construction_progress_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporting_date', sa.Date(), nullable=False),
    sa.Column('update_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('people_plan', sa.Integer(), nullable=False),
    sa.Column('equipment_plan', sa.Integer(), nullable=False),
    sa.Column('readiness', sa.DECIMAL(precision=17, scale=2), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.Integer(), nullable=False),
    sa.Column('construction_objects_id', sa.Integer(), nullable=False),
    sa.Column('progress_statuses_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_objects_id'], ['construction_objects.construction_objects_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['progress_statuses_id'], ['progress_statuses.progress_statuses_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('construction_progress_id'),
    sa.UniqueConstraint('construction_progress_id', 'reporting_date', name='construction_progress_unique')
    )
    op.create_table('object_completion',
    sa.Column('object_completion_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.DATE(), nullable=False),
    sa.Column('update_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('construction_objects_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_objects_id'], ['construction_objects.construction_objects_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_completion_id'),
    sa.UniqueConstraint('construction_objects_id', 'planned_date', name='object_completion_ak')
    )
    op.create_table('object_documents',
    sa.Column('object_documents_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('construction_objects_id', sa.Integer(), nullable=False),
    sa.Column('construction_documents_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_documents_id'], ['construction_documents.construction_documents_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['construction_objects_id'], ['construction_objects.construction_objects_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_documents_id'),
    sa.UniqueConstraint('construction_objects_id', 'construction_documents_id', name='object_documents_unique')
    )
    op.create_table('object_files',
    sa.Column('object_files_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idfilestorage', postgresql.UUID(), nullable=False),
    sa.Column('construction_objects_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['construction_objects_id'], ['construction_objects.construction_objects_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idfilestorage'], ['filestorage.idfilestorage'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_files_id'),
    sa.UniqueConstraint('idfilestorage', 'construction_objects_id', name='object_files_unique')
    )
    op.create_table('references_history',
    sa.Column('references_history_id', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('construction_objects_id', sa.Integer(), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.construction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['construction_objects_id'], ['construction_objects.construction_objects_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('references_history_id'),
    sa.UniqueConstraint('construction_objects_id', 'construction_id', 'end_date', name='references_history_ak')
    )
    op.create_table('completion_dates',
    sa.Column('completion_dates_id', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('contracts_id', sa.Integer(), nullable=False),
    sa.Column('contract_worktypes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_worktypes_id'], ['state_contract.contract_worktypes.contract_worktypes_id'], ),
    sa.ForeignKeyConstraint(['contracts_id'], ['state_contract.contracts.contracts_id'], ),
    sa.PrimaryKeyConstraint('completion_dates_id'),
    sa.UniqueConstraint('contracts_id', 'contract_worktypes_id', name='completion_dates_unique'),
    schema='state_contract'
    )
    op.create_table('works_list',
    sa.Column('works_list_id', sa.Integer(), nullable=False),
    sa.Column('element_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('begin_date', sa.DATE(), nullable=False),
    sa.Column('work_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('relevance_date', sa.DATE(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('element_types_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('plan', sa.DECIMAL(precision=17, scale=1), nullable=False),
    sa.Column('fact', sa.DECIMAL(precision=17, scale=1), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('work_types_id', sa.Integer(), nullable=True),
    sa.Column('construction_objects_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construction_objects_id'], ['construction_objects.construction_objects_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['element_types_id'], ['element_types.element_types_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['measure_units.unit_id'], ),
    sa.ForeignKeyConstraint(['work_types_id'], ['work_types.work_types_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('works_list_id'),
    sa.UniqueConstraint('construction_objects_id', 'element_types_id', name='worklist_unique')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works_list')
    op.drop_table('completion_dates', schema='state_contract')
    op.drop_table('references_history')
    op.drop_table('object_files')
    op.drop_table('object_documents')
    op.drop_table('object_completion')
    op.drop_table('construction_progress')
    op.drop_table('visited_objects')
    op.drop_table('contracts', schema='state_contract')
    op.drop_table('inspection_objects')
    op.drop_table('construction_objects')
    op.drop_table('construction_dynamics')
    op.drop_table('construction_documents')
    op.drop_table('construction')
    op.drop_table('work_trips')
    op.drop_table('military_unit', schema='military_unit')
    op.drop_table('subcategories_list')
    op.drop_table('protocol')
    op.drop_table('organizations_history', schema='organization')
    op.drop_table('organization_documents', schema='organization')
    op.drop_table('officials', schema='organization')
    op.drop_table('object_categories_list')
    op.drop_table('namemilitaryunit', schema='military_unit')
    op.drop_table('inspection_files')
    op.drop_table('construction_companies')
    op.drop_table('zones')
    op.drop_table('work_types')
    op.drop_table('contract_worktypes', schema='state_contract')
    op.drop_table('contract_statuses', schema='state_contract')
    op.drop_table('realty_types')
    op.drop_table('progress_statuses')
    op.drop_table('organizations', schema='organization')
    op.drop_table('military_ranks', schema='organization')
    op.drop_table('object_categories')
    op.drop_table('storage', schema='miv')
    op.drop_table('miv_logs', schema='miv')
    op.drop_table('sortarmedforces', schema='military_unit')
    op.drop_table('purposemu', schema='military_unit')
    op.drop_table('militarycity', schema='military_unit')
    op.drop_table('keyword', schema='military_unit')
    op.drop_table('combatarm', schema='military_unit')
    op.drop_table('meeting')
    op.drop_table('measure_units')
    op.drop_table('db_error', schema='logs')
    op.drop_table('location_types')
    op.drop_table('leadership_positions')
    op.drop_table('inspections')
    op.drop_table('filestorage')
    op.drop_table('fias')
    op.drop_table('element_types')
    op.drop_table('doctypes')
    op.drop_table('coordinates')
    op.drop_table('construction_types')
    op.drop_table('construction_subcategories')
    op.drop_table('construction_stages')
    op.drop_table('construction_categories')
    op.drop_table('commission')
    op.drop_table('OKSM')
    # ### end Alembic commands ###
