"""protocol_uq added

Revision ID: b98706037dd2
Revises: 5f1b055c83d3
Create Date: 2022-01-18 18:26:00.564981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98706037dd2'
down_revision = '5f1b055c83d3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('protocol_ak', 'protocol', ['protocol_num', 'protocol_date'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('protocol_ak', 'protocol', type_='unique')
    # ### end Alembic commands ###
