"""added military_unit_extension

Revision ID: bf919412aa89
Revises: dfa9c13193d3
Create Date: 2021-10-25 12:43:25.523251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf919412aa89'
down_revision = 'dfa9c13193d3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MilitaryUnit_extension',
    sa.Column('report_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('idMU', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idMU'], ['military_unit.military_unit.idMU'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idMU', 'start_date', name='military_unit_extension_pk'),
    schema='military_unit'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MilitaryUnit_extension', schema='military_unit')
    # ### end Alembic commands ###
