"""completion date deleting added

Revision ID: d6922bf73ef6
Revises: b98706037dd2
Create Date: 2022-02-02 17:54:19.683607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6922bf73ef6'
down_revision = 'b98706037dd2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('completion_dates_contracts_id_fkey', 'completion_dates', schema='state_contract', type_='foreignkey')
    op.create_foreign_key(None, 'completion_dates', 'contracts', ['contracts_id'], ['contracts_id'], source_schema='state_contract', referent_schema='state_contract', ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completion_dates', schema='state_contract', type_='foreignkey')
    op.create_foreign_key('completion_dates_contracts_id_fkey', 'completion_dates', 'contracts', ['contracts_id'], ['contracts_id'], source_schema='state_contract', referent_schema='state_contract')
    # ### end Alembic commands ###
