"""Create class classrank

Revision ID: d942c26c0733
Revises: 0ca3c0b7bbd2
Create Date: 2021-12-14 14:01:25.388396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd942c26c0733'
down_revision = '0ca3c0b7bbd2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_ranks',
    sa.Column('class_ranks_id', sa.INTEGER(), nullable=False, comment='Ид классного чина'),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False, comment='Наименование'),
    sa.PrimaryKeyConstraint('class_ranks_id'),
    sa.UniqueConstraint('fullname'),
    schema='organization'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_ranks', schema='organization')
    # ### end Alembic commands ###
