"""create court_decisions

Revision ID: dfa9c13193d3
Revises: 36ceacef8ed9
Create Date: 2021-10-19 13:02:36.427914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa9c13193d3'
down_revision = '36ceacef8ed9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_decisions',
    sa.Column('court_decisions_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False, comment='Полное название'),
    sa.PrimaryKeyConstraint('court_decisions_id'),
    sa.UniqueConstraint('fullname'),
    schema='courts'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('court_decisions', schema='courts')
    # ### end Alembic commands ###
