"""Create construction critial categories and update construction

Revision ID: fc667ad26138
Revises: 2e1edf4ffc3b
Create Date: 2021-10-11 17:11:16.833233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc667ad26138'
down_revision = '2e1edf4ffc3b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_critical_categories',
    sa.Column('construction_critical_categories_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('construction_critical_categories_id'),
    sa.UniqueConstraint('fullname')
    )
    op.add_column('construction', sa.Column('construction_critical_categories_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'construction', 'construction_critical_categories', ['construction_critical_categories_id'], ['construction_critical_categories_id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'construction', type_='foreignkey')
    op.drop_column('construction', 'construction_critical_categories_id')
    op.drop_table('construction_critical_categories')
    # ### end Alembic commands ###
