"""init

Revision ID: d13a90235b82
Revises: 
Create Date: 2020-07-27 10:32:18.558188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd13a90235b82'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filestorage',
    sa.Column('idfilestorage', postgresql.UUID(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('uri', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('mimeType', sa.VARCHAR(length=30), nullable=True),
    sa.Column('createdOn', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('authorid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idfilestorage', name=op.f('pk_filestorage'))
    )
    op.create_table('protocol',
    sa.Column('protocol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_num', sa.VARCHAR(length=20), nullable=False),
    sa.Column('protocol_date', sa.Date(), nullable=False),
    sa.Column('meetings_type_id', sa.Integer(), nullable=False),
    sa.Column('protocol_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('note', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('idfilestorage', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['idfilestorage'], ['filestorage.idfilestorage'], name=op.f('fk_protocol_idfilestorage_filestorage')),
    sa.PrimaryKeyConstraint('protocol_id', name=op.f('pk_protocol'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol')
    op.drop_table('filestorage')
    # ### end Alembic commands ###
