"""new revision

Revision ID: c160adcf5c21
Revises: 5332186a6b09
Create Date: 2020-07-27 16:01:15.478841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c160adcf5c21'
down_revision = '5332186a6b09'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
