"""init

Revision ID: ac5f33f08cfb
Revises: dba7fc3f06ce
Create Date: 2020-07-27 15:26:55.549737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5f33f08cfb'
down_revision = 'dba7fc3f06ce'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
