"""init

Revision ID: dba7fc3f06ce
Revises: d13a90235b82
Create Date: 2020-07-27 11:16:01.306531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba7fc3f06ce'
down_revision = 'd13a90235b82'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('meetings_type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('meetings_type_id', name=op.f('pk_meeting'))
    )
    op.alter_column('protocol', 'meetings_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('fk_protocol_meetings_type_id_meeting'), 'protocol', 'meeting', ['meetings_type_id'], ['meetings_type_id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_protocol_meetings_type_id_meeting'), 'protocol', type_='foreignkey')
    op.alter_column('protocol', 'meetings_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('meeting')
    # ### end Alembic commands ###
