"""new default createdOn

Revision ID: 5332186a6b09
Revises: ac5f33f08cfb
Create Date: 2020-07-27 15:32:25.362217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5332186a6b09'
down_revision = 'ac5f33f08cfb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
