ALREADY_DELETED_ERROR = {
    'protocol_ad': 'Этот Протокол уже удалили!',
    'contract_ad': 'Этот Контракт уже удалили!',
    'construction_company_ad': 'Эту Строительную Компанию уже удалили!',
    'construction_type_ad': 'Этот Тип Проекта уже удалили!',
    'realty_type_ad': 'Этот Тип Недвижимости уже удалили!',
    'construction_stage_ad': 'Этот Этап Строительства уже удалили!',
    'commission_ad': 'Эту Коммиссию уже удалили!',
    'construction_category_ad': 'Эту Категорию ИСП уже удалили!',
    'construction_subcategory_ad': 'Эту Подкатегорию ИСП уже удалили!',
    'location_type_ad': 'Этот Тип Местоположения уже удалили!',
    'doc_type_ad': 'Этот Тип Документа уже удалили!',
    'inspected_object_ad': 'Этот Объект уже удалили!',
    'oksm_ad': 'Эта запись в ОКСМ уже была удалена!',
    'organization_ad': 'Эту Организацию уже удалили!',
    'organization_history_ad': 'Этот Реквизит уже удалили!',
    'progress_status_ad': 'Этот Ход Строительства уже удалили!',
    'meeting_type_ad': 'Этот Тип Заседания уже удалили!',
    'leadership_position_ad': 'Эту Должность уже удалили!',
    'zone_ad': 'Эту Зону уже удалили!',
    'construction_critical_category_ad': 'Эту категорию критичного объекта уже удалили!',
    'reason_stopping_ad': 'Эту причину остановки СМР уже удалили!',
    'court_ad': 'Этот суд уже удалили!',
    'court_decision_ad': 'Это решение суда уже удалили',
    'military_unit_extension_ad': 'Это дополнительное описание в/ч уже удалили',
    'participant_status_ad': 'Этот статус участника судебных споров уже удалили'
}
